apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Chart.Name }}
spec:
  generators:
    - list:
        elements:
          - name: sealed-secrets
  template:
    metadata:
      name: '{{ `{{name}}`}}'
    spec:
      project: default
      source:
        repoURL: {{ .Values.source.repoURL }}
        targetRevision: {{ .Values.source.targetRevision }}
        path: '{{ .Values.source.basePath }}/{{ `{{name}}`}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
